- uses: azure/docker-login@v1
  with:
    login-server: learningacrpk01.azurecr.io
    username: ${{ secrets.learningacrpk01 }}
    password: ${{ secrets.TRGYchVLxvkMItE9HP9H0Ia8sB+bpmJ/7k4Ec9nKJL+ACRBB09mt }}

- name: Build and push image
  run: |
    docker build -t learningacrpk01.azurecr.io/learning-app:v1 .
    docker push learningacrpk01.azurecr.io/learning-app:v1
